# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/camProfile/core/main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toHar = QtWidgets.QRadioButton(self.centralWidget)
        self.toHar.setChecked(True)
        self.toHar.setObjectName("toHar")
        self.horizontalLayout_2.addWidget(self.toHar)
        self.toCy = QtWidgets.QRadioButton(self.centralWidget)
        self.toCy.setObjectName("toCy")
        self.horizontalLayout_2.addWidget(self.toCy)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showBase = QtWidgets.QCheckBox(self.centralWidget)
        self.showBase.setChecked(True)
        self.showBase.setObjectName("showBase")
        self.horizontalLayout.addWidget(self.showBase)
        self.showRoute = QtWidgets.QCheckBox(self.centralWidget)
        self.showRoute.setChecked(True)
        self.showRoute.setObjectName("showRoute")
        self.horizontalLayout.addWidget(self.showRoute)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.baseVal = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.baseVal.setMinimum(1.0)
        self.baseVal.setMaximum(10.0)
        self.baseVal.setProperty("value", 3.0)
        self.baseVal.setObjectName("baseVal")
        self.horizontalLayout.addWidget(self.baseVal)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.liftVal = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.liftVal.setMinimum(1.0)
        self.liftVal.setMaximum(10.0)
        self.liftVal.setProperty("value", 1.0)
        self.liftVal.setObjectName("liftVal")
        self.horizontalLayout.addWidget(self.liftVal)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cutterRadiusVal = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.cutterRadiusVal.setMinimum(0.5)
        self.cutterRadiusVal.setMaximum(10.0)
        self.cutterRadiusVal.setProperty("value", 0.5)
        self.cutterRadiusVal.setObjectName("cutterRadiusVal")
        self.horizontalLayout.addWidget(self.cutterRadiusVal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.rotateBar = QtWidgets.QSlider(self.centralWidget)
        self.rotateBar.setMaximum(360)
        self.rotateBar.setOrientation(QtCore.Qt.Horizontal)
        self.rotateBar.setObjectName("rotateBar")
        self.horizontalLayout_3.addWidget(self.rotateBar)
        self.rotateAngle = QtWidgets.QSpinBox(self.centralWidget)
        self.rotateAngle.setMaximum(360)
        self.rotateAngle.setSingleStep(10)
        self.rotateAngle.setObjectName("rotateAngle")
        self.horizontalLayout_3.addWidget(self.rotateAngle)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.canvasLayout = QtWidgets.QVBoxLayout()
        self.canvasLayout.setObjectName("canvasLayout")
        self.horizontalLayout_4.addLayout(self.canvasLayout)
        self.zoomBar = QtWidgets.QSlider(self.centralWidget)
        self.zoomBar.setMinimum(1)
        self.zoomBar.setMaximum(50)
        self.zoomBar.setPageStep(1)
        self.zoomBar.setProperty("value", 30)
        self.zoomBar.setOrientation(QtCore.Qt.Vertical)
        self.zoomBar.setObjectName("zoomBar")
        self.horizontalLayout_4.addWidget(self.zoomBar)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toHar.setText(_translate("MainWindow", "Harmonic"))
        self.toCy.setText(_translate("MainWindow", "Cycloidal"))
        self.label_4.setText(_translate("MainWindow", "Unit: inch"))
        self.showBase.setText(_translate("MainWindow", "Base circle"))
        self.showRoute.setText(_translate("MainWindow", "Cutter Route"))
        self.label_3.setText(_translate("MainWindow", "Base Circle:"))
        self.label_2.setText(_translate("MainWindow", "Lift:"))
        self.label.setText(_translate("MainWindow", "Cutter radius:"))
        self.label_5.setText(_translate("MainWindow", "Rotate Angle:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

